on:
  # Only run this workflow when a release is published.
  # To modify this workflow when other events occur, see:
  #   - https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
  #   - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  #   - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  #
  # Note that some steps may depend on context variables that are only
  # available for release events, so if you add other events, you may need to
  # alter other parts of this workflow.
  release:
    types: [published]

name: Release FoundryVTT Module

jobs:
  check_version:
    name: Check FoundryVTT module version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check for new version
        id: check_for_new_version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          create-tag: false
          version-command: |
            jq -r .version module.json
    outputs:
      module_previous_version: v${{ steps.check_for_new_version.outputs.previous-version }}
      module_current_version: v${{ steps.check_for_new_version.outputs.current-version }}
  build:
    name: Release FoundryVTT Module
    runs-on: ubuntu-latest
    needs: check_version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update download URL
        id: update_module_download_url
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          download: https://github.com/${{ github.repository }}/releases/download/${{ needs.check_version.outputs.module_current_version }}/${{ github.event.repository.name }}.zip
      - name: Install dependencies
        id: install_dependencies
        run: yarn install
      - name: Build package
        id: build
        run: yarn build
      - name: Package module
        working-directory: ./dist
        run: |
          zip -r ../${{ github.event.repository.name }}.zip *
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.check_version.outputs.module_current_version }}
          release_name: Release ${{ needs.check_version.outputs.module_current_version }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
